# Generated by Django 5.0 on 2025-09-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
