# Generated by Django 5.0 on 2025-09-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_amount_left'),
    ]

    operations = [
    ]
